#!/usr/bin/env python3
"""Generate German fish pages from English ones."""
import os
import re
import shutil

# Directories
EN_FISH_DIR = "fish"
DE_FISH_DIR = "de/fische"

# Create output directory
os.makedirs(DE_FISH_DIR, exist_ok=True)

# Translation patterns (English -> German)
TRANSLATIONS = [
    # Meta/HTML
    (r'lang="en"', 'lang="de"'),
    
    # Title and meta tags
    (r'Care Guide \| FishFinder', 'Pflegeanleitung | FishFinder'),
    (r'Care Guide, Tank Size & Compatibility', 'Pflegeanleitung, Aquariumgröße & Kompatibilität'),
    
    # Meta descriptions
    (r'Complete (.+?) care guide\. Learn about tank size', r'Komplette \1 Pflegeanleitung. Erfahre mehr über Beckengröße'),
    (r'water parameters', 'Wasserwerte'),
    (r'compatible tankmates', 'verträgliche Mitbewohner'),
    (r'expert care tips', 'Experten-Pflegetipps'),
    
    # Common fish descriptions
    (r'A centerpiece fish for larger tanks', 'Ein Blickfang für größere Aquarien'),
    (r'A centerpiece fish', 'Ein Blickfang-Fisch'),
    (r'for larger tanks', 'für größere Aquarien'),
    (r'Perfect for beginners', 'Perfekt für Anfänger'),
    (r'Great for beginners', 'Toll für Anfänger'),
    (r'Ideal for beginners', 'Ideal für Anfänger'),
    (r'Easy to care for', 'Pflegeleicht'),
    (r'Hardy and adaptable', 'Robust und anpassungsfähig'),
    (r'Elegant cichlids', 'Elegante Buntbarsche'),
    (r'with tall, triangular bodies', 'mit hohen, dreieckigen Körpern'),
    (r'Colorful and active', 'Farbenfroh und aktiv'),
    (r'Peaceful community fish', 'Friedlicher Gesellschaftsfisch'),
    (r'Popular freshwater fish', 'Beliebter Süßwasserfisch'),
    (r'schooling fish', 'Schwarmfisch'),
    (r'bottom-dwelling', 'bodenbewohnend'),
    (r'surface-dwelling', 'oberflächenbewohnend'),
    (r'mid-dwelling', 'mittelzonenbewohnend'),
    
    # Stats - common values (manual conversion: gal*3.785, inch*2.54)
    (r'>5 Gallons<', '>19L<'),
    (r'>10 Gallons<', '>38L<'),
    (r'>15 Gallons<', '>57L<'),
    (r'>20 Gallons<', '>75L<'),
    (r'>30 Gallons<', '>114L<'),
    (r'>40 Gallons<', '>151L<'),
    (r'>50 Gallons<', '>189L<'),
    (r'>55 Gallons<', '>208L<'),
    (r'>75 Gallons<', '>284L<'),
    (r'>100 Gallons<', '>379L<'),
    (r'>125 Gallons<', '>473L<'),
    (r'>1 inch<', '>3cm<'),
    (r'>2 inches<', '>5cm<'),
    (r'>3 inches<', '>8cm<'),
    (r'>4 inches<', '>10cm<'),
    (r'>5 inches<', '>13cm<'),
    (r'>6 inches<', '>15cm<'),
    (r'>8 inches<', '>20cm<'),
    (r'>10 inches<', '>25cm<'),
    (r'>12 inches<', '>30cm<'),
    (r'>18 inches<', '>46cm<'),
    (r'>24 inches<', '>61cm<'),
    
    # Care tips
    (r'Minimum 5-gallon tank required', 'Mindestens 19L Aquarium erforderlich'),
    (r'Minimum 10-gallon tank required', 'Mindestens 38L Aquarium erforderlich'),
    (r'Minimum 20-gallon tank required', 'Mindestens 75L Aquarium erforderlich'),
    (r'Minimum 30-gallon tank required', 'Mindestens 114L Aquarium erforderlich'),
    (r'Minimum 40-gallon tank required', 'Mindestens 151L Aquarium erforderlich'),
    (r'Minimum 50-gallon tank required', 'Mindestens 189L Aquarium erforderlich'),
    (r'Minimum 55-gallon tank required', 'Mindestens 208L Aquarium erforderlich'),
    (r'Minimum 75-gallon tank required', 'Mindestens 284L Aquarium erforderlich'),
    (r'Feed 1-2 times daily', 'Füttere 1-2 mal täglich'),
    (r'Feed 2-3 times daily', 'Füttere 2-3 mal täglich'),
    (r'Keep in groups', 'In Gruppen halten'),
    (r'Keep in schools', 'In Schwärmen halten'),
    (r'Provide hiding spots', 'Versteckmöglichkeiten bieten'),
    (r'Provide plants', 'Pflanzen bieten'),
    (r'Weekly water changes', 'Wöchentlicher Wasserwechsel'),
    (r'Regular water changes', 'Regelmäßiger Wasserwechsel'),
    (r'Stable water parameters', 'Stabile Wasserwerte'),
    (r'Needs pristine water', 'Benötigt sauberes Wasser'),
    (r'Avoid aggressive tankmates', 'Aggressive Mitbewohner vermeiden'),
    (r'Peaceful community fish', 'Friedlicher Gesellschaftsfisch'),
    
    # URLs
    (r'href="/fish/', 'href="/de/fische/'),
    (r'href="/"', 'href="/de/"'),
    (r'href="/search/"', 'href="/de/suche/"'),
    (r'href="/quiz/"', 'href="/de/quiz/"'),
    (r'href="/compatibility/"', 'href="/de/kompatibilitaet/"'),
    (r'href="/setups/"', 'href="/de/einrichtungen/"'),
    (r'href="/faq/"', 'href="/de/faq/"'),
    (r'href="/articles/"', 'href="/de/artikel/"'),
    (r'href="/about/"', 'href="/de/ueber/"'),
    (r'href="/compare/"', 'href="/de/kompatibilitaet/"'),
    (r'href="../search/"', 'href="../suche/"'),
    (r'href="../quiz/"', 'href="../quiz/"'),
    (r'href="../compatibility/"', 'href="../kompatibilitaet/"'),
    (r'fishfinder\.guide/fish/', 'fishfinder.guide/de/fische/'),
    
    # Navigation
    (r'>Browse Fish<', '>Fische durchsuchen<'),
    (r'>Browse<', '>Durchsuchen<'),
    (r'>Quiz<', '>Quiz<'),
    (r'>Compatibility<', '>Kompatibilität<'),
    (r'>Find Your Fish<', '>Finde deinen Fisch<'),
    (r'>Browse Setups<', '>Einrichtungen ansehen<'),
    (r'>Home<', '>Startseite<'),
    (r'>Fish<', '>Fische<'),
    (r'>Articles<', '>Artikel<'),
    
    # Care Guide sections
    (r'>Care Guide<', '>Pflegeanleitung<'),
    (r'>Quick Facts<', '>Schnelle Fakten<'),
    (r'>Tank Requirements<', '>Aquariumanforderungen<'),
    (r'>Water Parameters<', '>Wasserwerte<'),
    (r'>Temperament<', '>Temperament<'),
    (r'>Diet<', '>Ernährung<'),
    (r'>Feeding<', '>Fütterung<'),
    (r'>Tank Mates<', '>Mitbewohner<'),
    (r'>Compatible Tank Mates<', '>Verträgliche Mitbewohner<'),
    (r'>Avoid<', '>Vermeiden<'),
    (r'>Best For<', '>Geeignet für<'),
    (r'>Not Ideal For<', '>Nicht geeignet für<'),
    (r'>Description<', '>Beschreibung<'),
    (r'>Overview<', '>Überblick<'),
    (r'>Care Level<', '>Pflegestufe<'),
    (r'>Difficulty<', '>Schwierigkeit<'),
    (r'>Breeding<', '>Zucht<'),
    (r'>Behavior<', '>Verhalten<'),
    (r'>Habitat<', '>Lebensraum<'),
    (r'>Origin<', '>Herkunft<'),
    (r'>Natural Habitat<', '>Natürlicher Lebensraum<'),
    
    # Stats labels
    (r'>Tank Size<', '>Aquariumgröße<'),
    (r'>Min Tank \((\d+)gal\)<', r'>Min. Aquarium (\1gal)<'),
    (r'>Adult Size \(([^)]+)\)<', r'>Erwachsenengröße (\1)<'),
    (r'>Minimum Tank<', '>Mindestaquarium<'),
    (r'>Temperature<', '>Temperatur<'),
    (r'>Size<', '>Größe<'),
    (r'>Adult Size<', '>Erwachsenengröße<'),
    (r'>Lifespan<', '>Lebenserwartung<'),
    (r'>pH Range<', '>pH-Bereich<'),
    (r'>Hardness<', '>Härte<'),
    (r'>Max Size<', '>Max. Größe<'),
    
    # Temperament values
    (r'>peaceful<', '>friedlich<'),
    (r'>Peaceful<', '>Friedlich<'),
    (r'>semi-aggressive<', '>semi-aggressiv<'),
    (r'>Semi-Aggressive<', '>Semi-Aggressiv<'),
    (r'>Semi-aggressive<', '>Semi-aggressiv<'),
    (r'>aggressive<', '>aggressiv<'),
    (r'>Aggressive<', '>Aggressiv<'),
    
    # Care levels
    (r'>Beginner<', '>Anfänger<'),
    (r'>beginner<', '>anfänger<'),
    (r'>Easy<', '>Einfach<'),
    (r'>easy<', '>einfach<'),
    (r'>Intermediate<', '>Fortgeschritten<'),
    (r'>intermediate<', '>fortgeschritten<'),
    (r'>Moderate<', '>Mittel<'),
    (r'>moderate<', '>mittel<'),
    (r'>Advanced<', '>Experte<'),
    (r'>advanced<', '>experte<'),
    (r'>Hard<', '>Schwer<'),
    (r'>hard<', '>schwer<'),
    
    # Schooling
    (r'>Schooling<', '>Schwarmfisch<'),
    (r'>schooling<', '>schwarmfisch<'),
    (r'>School Size<', '>Schwarmgröße<'),
    (r'>Solo<', '>Einzelhaltung<'),
    (r'>solo<', '>einzelhaltung<'),
    (r'>Yes<', '>Ja<'),
    (r'>No<', '>Nein<'),
    (r'>Can Keep Solo<', '>Einzelhaltung möglich<'),
    
    # Categories
    (r'>tetra<', '>salmler<'),
    (r'>Tetra<', '>Salmler<'),
    (r'>livebearer<', '>lebendgebärend<'),
    (r'>Livebearer<', '>Lebendgebärend<'),
    (r'>catfish<', '>wels<'),
    (r'>Catfish<', '>Wels<'),
    (r'>cichlid<', '>buntbarsch<'),
    (r'>Cichlid<', '>Buntbarsch<'),
    (r'>shrimp<', '>garnele<'),
    (r'>Shrimp<', '>Garnele<'),
    (r'>snail<', '>schnecke<'),
    (r'>Snail<', '>Schnecke<'),
    (r'>loach<', '>schmerle<'),
    (r'>Loach<', '>Schmerle<'),
    (r'>barb<', '>barbe<'),
    (r'>Barb<', '>Barbe<'),
    (r'>gourami<', '>gurami<'),
    (r'>Gourami<', '>Gurami<'),
    (r'>rasbora<', '>rasbora<'),
    (r'>Rasbora<', '>Rasbora<'),
    (r'>danio<', '>bärbling<'),
    (r'>Danio<', '>Bärbling<'),
    (r'>pleco<', '>wels<'),
    (r'>Pleco<', '>Wels<'),
    (r'>killifish<', '>killifisch<'),
    (r'>Killifish<', '>Killifisch<'),
    (r'>rainbow<', '>regenbogenfisch<'),
    (r'>Rainbow<', '>Regenbogenfisch<'),
    
    # Diet types
    (r'>Omnivore<', '>Allesfresser<'),
    (r'>omnivore<', '>allesfresser<'),
    (r'>Carnivore<', '>Fleischfresser<'),
    (r'>carnivore<', '>fleischfresser<'),
    (r'>Herbivore<', '>Pflanzenfresser<'),
    (r'>herbivore<', '>pflanzenfresser<'),
    (r'>Insectivore<', '>Insektenfresser<'),
    (r'>Algae Eater<', '>Algenfresser<'),
    (r'>Filter Feeder<', '>Filtrierer<'),
    
    # Other labels
    (r'>Compatibility Checker<', '>Kompatibilitätsprüfer<'),
    (r'>years<', '>Jahre<'),
    (r'>year<', '>Jahr<'),
    (r'(\d+) years', r'\1 Jahre'),
    (r'(\d+)yr<', r'\1J<'),
    (r'Temperature:', 'Temperatur:'),
    (r'Compatible With', 'Kompatibel mit'),
    (r'Avoid Keeping With', 'Nicht zusammen halten mit'),
    (r'Avoid Keeping', 'Nicht zusammen halten'),
    (r'>months<', '>Monate<'),
    (r'>inches<', '>Zoll<'),
    (r'>gallons<', '>Gallonen<'),
    
    # Best For phrases
    (r'Best for beginners', 'Ideal für Anfänger'),
    (r'Best for community tanks', 'Ideal für Gesellschaftsaquarien'),
    (r'Best for planted tanks', 'Ideal für Pflanzenaquarien'),
    (r'Great for beginners', 'Toll für Anfänger'),
    (r'Perfect for beginners', 'Perfekt für Anfänger'),
    (r'Ideal for beginners', 'Ideal für Anfänger'),
    (r'Easy to care for', 'Leicht zu pflegen'),
    (r'Hardy and resilient', 'Robust und widerstandsfähig'),
    (r'Low maintenance', 'Pflegeleicht'),
    (r'Peaceful community fish', 'Friedlicher Gesellschaftsfisch'),
    (r'Great cleanup crew', 'Tolles Aufräumteam'),
    (r'Algae eater', 'Algenfresser'),
    (r'Active swimmer', 'Aktiver Schwimmer'),
    (r'Colorful and vibrant', 'Farbenfroh und lebhaft'),
    (r'Beautiful fins', 'Schöne Flossen'),
    (r'Unique appearance', 'Einzigartiges Aussehen'),
    (r'Interesting behavior', 'Interessantes Verhalten'),
    
    # Not Ideal For phrases
    (r'Not for beginners', 'Nicht für Anfänger'),
    (r'Not ideal for beginners', 'Nicht ideal für Anfänger'),
    (r'Needs experienced keeper', 'Erfordert erfahrenen Halter'),
    (r'Requires large tank', 'Benötigt großes Aquarium'),
    (r'May eat small fish', 'Kann kleine Fische fressen'),
    (r'Can be aggressive', 'Kann aggressiv sein'),
    (r'Fin nipper', 'Flossenbeißer'),
    (r'Sensitive to water quality', 'Empfindlich bei Wasserqualität'),
    (r'Needs soft water', 'Benötigt weiches Wasser'),
    (r'Needs specific pH', 'Benötigt spezifischen pH-Wert'),
    
    # Breadcrumb schema
    (r'"name": "Home"', '"name": "Startseite"'),
    (r'"name": "Fish"', '"name": "Fische"'),
    
    # Section headings
    (r'>About ([^<]+)<', r'>Über \1<'),
    (r'>Tank Setup<', '>Aquarium-Einrichtung<'),
    (r'>Tank Mate Compatibility<', '>Mitbewohner-Kompatibilität<'),
    (r'Tank Setup', 'Aquarium-Einrichtung'),
    (r'Diet & Feeding', 'Ernährung & Fütterung'),
    (r'Diet type:', 'Ernährungstyp:'),
    (r'Expert Tips', 'Experten-Tipps'),
    (r'>Omnivore<', '>Allesfresser<'),
    (r'>Carnivore<', '>Fleischfresser<'),
    (r'>Herbivore<', '>Pflanzenfresser<'),
    (r': Omnivore', ': Allesfresser'),
    (r': Carnivore', ': Fleischfresser'),
    (r': Herbivore', ': Pflanzenfresser'),
    (r'>Care Requirements<', '>Pflegeanforderungen<'),
    (r'>Care Tips<', '>Pflegetipps<'),
    (r'>Fish Quiz<', '>Fisch-Quiz<'),
    
    # Tank mates examples
    (r'>Larger Tetras<', '>Größere Salmler<'),
    (r'>Small Tetras<', '>Kleine Salmler<'),
    (r'>Small Fish<', '>Kleine Fische<'),
    (r'>Large Fish<', '>Große Fische<'),
    (r'>Fin Nippers<', '>Flossenbeißer<'),
    (r'>Aggressive Cichlids<', '>Aggressive Buntbarsche<'),
    (r'>Peaceful Catfish<', '>Friedliche Welse<'),
    (r'>Bottom Dwellers<', '>Bodenbewohner<'),
    (r'>Corydoras<', '>Panzerwelse<'),
    (r'>Plecos<', '>Saugwelse<'),
    (r'>Livebearers<', '>Lebendgebärende<'),
    (r'>Other Gouramis<', '>Andere Guramis<'),
    (r'>Gouramis<', '>Guramis<'),
    (r'>Compare<', '>Vergleichen<'),
    (r'>Not compatible<', '>Nicht kompatibel<'),
    (r'>Compatible<', '>Kompatibel<'),
    (r'>FAQ<', '>FAQ<'),
    (r'>Shrimp<', '>Garnelen<'),
    (r'>Snails<', '>Schnecken<'),
    (r'>Dwarf Shrimp<', '>Zwerggarnelen<'),
    (r'>Min School<', '>Min. Schwarm<'),
    (r'Check more combinations with our Compatibility Checker', 'Prüfe weitere Kombinationen mit unserem Kompatibilitätsprüfer'),
    (r'Find compatible tankmates for your (.+)', r'Finde verträgliche Mitbewohner für deinen \1'),
    (r'Find verträgliche Mitbewohner for your (.+)', r'Finde verträgliche Mitbewohner für deinen \1'),
    
    # CTA section
    (r'Build Your Perfect Community Tank', 'Erstelle dein perfektes Gesellschaftsaquarium'),
    (r'Find compatible tankmates', 'Finde verträgliche Mitbewohner'),
    (r'Check compatibility', 'Kompatibilität prüfen'),
    (r'Take the quiz', 'Mach das Quiz'),
    (r'Find your fish', 'Finde deinen Fisch'),
    (r'Find Your Perfect Fish', 'Finde deinen perfekten Fisch'),
    (r'Browse all fish', 'Alle Fische durchsuchen'),
    (r'View all fish', 'Alle Fische ansehen'),
    
    # Footer
    (r'Made with', 'Erstellt mit'),
    (r'for fish lovers everywhere', 'für Fischliebhaber überall'),
    (r'for fish lovers', 'für Fischliebhaber'),
    
    # Common phrases
    (r'fish found', 'Fische gefunden'),
    (r'No fish found', 'Keine Fische gefunden'),
    (r'Loading', 'Laden'),
    (r'Search', 'Suchen'),
    (r'Filter', 'Filtern'),
    (r'Sort by', 'Sortieren nach'),
    (r'Clear all', 'Alle löschen'),
    (r'Reset', 'Zurücksetzen'),
    (r'Apply', 'Anwenden'),
    (r'Show more', 'Mehr anzeigen'),
    (r'Show less', 'Weniger anzeigen'),
    (r'Read more', 'Mehr lesen'),
    (r'Learn more', 'Mehr erfahren'),
    (r'View details', 'Details ansehen'),
    
    # Language switcher - update to show DE as active
    (r'<span class="font-bold text-cyan-600">EN</span>', '<a href="/" class="text-slate-500 hover:text-cyan-600 transition">EN</a>'),
    (r'<a href="/es/" class="text-slate-500 hover:text-cyan-600 transition">ES</a>', '<span class="font-bold text-cyan-600">DE</span>'),
    
    # More UI translations
    (r'Compare with Others', 'Mit anderen vergleichen'),
    (r'>Compatibility Checker<', '>Kompatibilitätsprüfer<'),
    (r'Compatibility Checker', 'Kompatibilitätsprüfer'),
    (r'Varied diet recommended', 'Abwechslungsreiche Ernährung empfohlen'),
    (r'Category: Cichlid', 'Kategorie: Buntbarsch'),
    (r'Category: Tetra', 'Kategorie: Salmler'),
    (r'Category: Livebearer', 'Kategorie: Lebendgebärend'),
    (r'Category: Catfish', 'Kategorie: Wels'),
    (r'Category: Shrimp', 'Kategorie: Garnele'),
    (r'Category: Snail', 'Kategorie: Schnecke'),
    (r'Category: Loach', 'Kategorie: Schmerle'),
    (r'Category: Barb', 'Kategorie: Barbe'),
    (r'Category: Gourami', 'Kategorie: Gurami'),
    (r'Category: Rasbora', 'Kategorie: Rasbora'),
    (r'Category: Pleco', 'Kategorie: Wels'),
    (r'Category: Killifish', 'Kategorie: Killifisch'),
    (r'Category: Betta', 'Kategorie: Kampffisch'),
    (r'Category: Goldfish', 'Kategorie: Goldfisch'),
    (r'Category: Rainbow', 'Kategorie: Regenbogenfisch'),
    (r'Category: Corydoras', 'Kategorie: Panzerwels'),
    (r', and ', ', und '),
    (r' and ', ' und '),
    (r'\(5 gallons\)', '(19L)'),
    (r'\(10 gallons\)', '(38L)'),
    (r'\(15 gallons\)', '(57L)'),
    (r'\(20 gallons\)', '(75L)'),
    (r'\(30 gallons\)', '(114L)'),
    (r'\(40 gallons\)', '(151L)'),
    (r'\(50 gallons\)', '(189L)'),
    (r'\(55 gallons\)', '(208L)'),
    (r'\(75 gallons\)', '(284L)'),
    (r'\(100 gallons\)', '(379L)'),
    
    # Additional care notes
    (r'Tall tank needed', 'Hohes Becken erforderlich'),
    (r'may eat small fish', 'kann kleine Fische fressen'),
    (r'can be territorial when breeding', 'kann beim Brüten territorial werden'),
    (r'needs experienced keeper', 'erfordert erfahrenen Halter'),
    (r'sensitive to water quality', 'empfindlich bei Wasserqualität'),
    (r'requires pristine water', 'benötigt sauberes Wasser'),
    (r'not suitable for small tanks', 'nicht für kleine Becken geeignet'),
    (r'needs a lid', 'benötigt eine Abdeckung'),
    (r'may jump', 'kann springen'),
    (r'nocturnal', 'nachtaktiv'),
    (r'diurnal', 'tagaktiv'),
    (r'shy at first', 'anfangs schüchtern'),
    (r'very active', 'sehr aktiv'),
    
    # Fish descriptions
    (r'livebearers', 'Lebendgebärende'),
    (r'Livebearers', 'Lebendgebärende'),
    (r'Breed readily in home aquariums', 'Vermehren sich leicht im Heimaquarium'),
    (r'Many color varieties', 'Viele Farbvarianten'),
    (r'color varieties', 'Farbvarianten'),
    (r'Easy to breed', 'Leicht zu züchten'),
    (r'Hardy species', 'Robuste Art'),
    (r'Hardy and adaptable', 'Robust und anpassungsfähig'),
    (r'Beginner friendly', 'Anfängerfreundlich'),
    (r'beginner friendly', 'anfängerfreundlich'),
    (r'Low maintenance', 'Pflegeleicht'),
    (r'low maintenance', 'pflegeleicht'),
    (r'Active swimmers', 'Aktive Schwimmer'),
    (r'active swimmers', 'aktive Schwimmer'),
    (r'schooling species', 'Schwarmfischart'),
    (r'community tank', 'Gesellschaftsaquarium'),
    (r'planted tanks', 'Pflanzenaquarien'),
    (r'nano tanks', 'Nano-Aquarien'),
    
    # Tank mates
    (r'>Large Cichlids<', '>Große Buntbarsche<'),
    (r'>Small Cichlids<', '>Kleine Buntbarsche<'),
    (r'>Fin Nippers<', '>Flossenbeißer<'),
    (r'>Other Livebearers<', '>Andere Lebendgebärende<'),
    (r'>Bottom Dwellers<', '>Bodenbewohner<'),
    (r'Avoid Keeping With', 'Nicht zusammen halten mit'),
    
    # Guppy/livebearer specific
    (r'Keep more females than males', 'Mehr Weibchen als Männchen halten'),
    (r'prolific breeders', 'produktive Züchter'),
    (r'easy for beginners', 'einfach für Anfänger'),
    
    # More care tips
    (r'Provide plenty of plants', 'Viele Pflanzen bieten'),
    (r'needs hiding spots', 'benötigt Verstecke'),
    (r'Regular water changes', 'Regelmäßige Wasserwechsel'),
    (r'Avoid overfeeding', 'Überfütterung vermeiden'),
    (r'Monitor water quality', 'Wasserqualität überwachen'),
    (r'Hardy and peaceful', 'Robust und friedlich'),
    (r'Great for community tanks', 'Toll für Gesellschaftsaquarien'),
    
    # Fish descriptions
    (r'One of the most peaceful', 'Einer der friedlichsten'),
    (r'Bright yellow coloration', 'Leuchtend gelbe Färbung'),
    (r'Bright coloration', 'Leuchtende Färbung'),
    (r'>Other Mbuna<', '>Andere Mbuna<'),
    (r'>African Cichlids<', '>Afrikanische Buntbarsche<'),
    (r'>South American Cichlids<', '>Südamerikanische Buntbarsche<'),
    (r'>Central American Cichlids<', '>Mittelamerikanische Buntbarsche<'),
    (r'>Peaceful Community Fish<', '>Friedliche Gesellschaftsfische<'),
    (r'>Peaceful Fish<', '>Friedliche Fische<'),
    (r'>Community Fish<', '>Gesellschaftsfische<'),
    (r'>Aggressive Fish<', '>Aggressive Fische<'),
    (r'>Semi-Aggressive Fish<', '>Semi-aggressive Fische<'),
    (r'>Small Peaceful Fish<', '>Kleine friedliche Fische<'),
    (r'>Larger Tetras<', '>Größere Salmler<'),
    (r'>Small Tetras<', '>Kleine Salmler<'),
    (r'>Other Livebearers<', '>Andere Lebendgebärende<'),
    (r'>Other Gouramis<', '>Andere Guramis<'),
    (r'>Other Cichlids<', '>Andere Buntbarsche<'),
    (r'>Dwarf Cichlids<', '>Zwergbuntbarsche<'),
    (r'>Peaceful Catfish<', '>Friedliche Welse<'),
    (r'>Larger Fish<', '>Größere Fische<'),
    (r'>Smaller Fish<', '>Kleinere Fische<'),
    (r'>Invertebrates<', '>Wirbellose<'),
    (r'>Snails<', '>Schnecken<'),
    (r'>Shrimp<', '>Garnelen<'),
    (r'>Large Peaceful Fish<', '>Große friedliche Fische<'),
    (r'>Larger Peaceful Fish<', '>Größere friedliche Fische<'),
    (r'>Small Peaceful Fish<', '>Kleine friedliche Fische<'),
    (r'>Peaceful Cichlids<', '>Friedliche Buntbarsche<'),
    (r'>Peaceful Tetras<', '>Friedliche Salmler<'),
    (r'>Very Active Fish<', '>Sehr aktive Fische<'),
    (r'>Active Fish<', '>Aktive Fische<'),
    (r'>Slow Moving Fish<', '>Langsame Fische<'),
    (r'>Fast Swimming Fish<', '>Schnell schwimmende Fische<'),
    (r'>Similar Sized Fish<', '>Ähnlich große Fische<'),
    (r'>Tropical Fish<', '>Tropische Fische<'),
    (r'>Coldwater Fish<', '>Kaltwasserfische<'),
    (r'Hard alkaline water required', 'Hartes alkalisches Wasser erforderlich'),
    (r'keep with other Mbuna', 'mit anderen Mbuna halten'),
    (r'overstocking reduces aggression', 'Überbesatz reduziert Aggression'),
    (r'Hardy and colorful', 'Robust und farbenfroh'),
    (r'Popular aquarium fish', 'Beliebter Aquarienfisch'),
    (r'Easy to keep', 'Einfach zu halten'),
    (r'Striking appearance', 'Auffällige Erscheinung'),
    (r'Beautiful finnage', 'Schöne Beflossung'),
    (r'Interesting behavior', 'Interessantes Verhalten'),
    (r'Great algae eater', 'Toller Algenfresser'),
    (r'Excellent scavenger', 'Ausgezeichneter Resteverwerter'),
    (r'Nocturnal species', 'Nachtaktive Art'),
    (r'Shy species', 'Scheue Art'),
    (r'Bold and active', 'Mutig und aktiv'),
    
    # More fish descriptions
    (r'Hardy and common', 'Robust und verbreitet'),
    (r'Also called', 'Auch bekannt als'),
    (r'Can be territorial', 'Kann territorial sein'),
    (r'Three-spot Gourami', 'Punktierter Fadenfisch'),
    (r'common gourami', 'verbreiteter Gurami'),
    (r'Hardy and peaceful', 'Robust und friedlich'),
    (r'Hardy and active', 'Robust und aktiv'),
    (r'Shy and peaceful', 'Scheu und friedlich'),
    (r'Active and colorful', 'Aktiv und farbenfroh'),
    (r'Peaceful schooling fish', 'Friedlicher Schwarmfisch'),
    (r'Popular beginner fish', 'Beliebter Anfängerfisch'),
    (r'Classic aquarium fish', 'Klassischer Aquarienfisch'),
    (r'Great community fish', 'Toller Gesellschaftsfisch'),
    (r'Excellent algae eater', 'Ausgezeichneter Algenfresser'),
    (r'Loves planted tanks', 'Liebt bepflanzte Aquarien'),
    (r'Needs warm water', 'Benötigt warmes Wasser'),
    (r'Prefers soft water', 'Bevorzugt weiches Wasser'),
    (r'Requires good filtration', 'Benötigt gute Filterung'),
    
    # Common description phrases
    (r'Very energetic', 'Sehr energisch'),
    (r'Very peaceful', 'Sehr friedlich'),
    (r'Very social', 'Sehr gesellig'),
    (r'Very hardy', 'Sehr robust'),
    (r'Very active', 'Sehr aktiv'),
    (r'Very aggressive', 'Sehr aggressiv'),
    (r'Very popular', 'Sehr beliebt'),
    (r'Great snail controller', 'Toller Schneckenfresser'),
    (r'Great tank cleaners', 'Tolle Aquarienreiniger'),
    (r'Great with', 'Toll mit'),
    (r'Excellent snail control', 'Ausgezeichnete Schneckenkontrolle'),
    (r'Excellent tank cleaners', 'Ausgezeichnete Aquarienreiniger'),
    (r'Keep in large groups', 'In großen Gruppen halten'),
    (r'Keep in groups', 'In Gruppen halten'),
    (r'Keep in schools', 'In Schwärmen halten'),
    (r'known for', 'bekannt für'),
    (r'fin nipping', 'Flossenbeißen'),
    (r'to curb aggression', 'um Aggression zu reduzieren'),
    (r'Prefers slightly cooler water', 'Bevorzugt etwas kühleres Wasser'),
    (r'Prefers cooler water', 'Bevorzugt kühleres Wasser'),
    (r'Prefers warmer water', 'Bevorzugt wärmeres Wasser'),
    (r'Males are more colorful', 'Männchen sind farbenfroher'),
    (r'Males develop', 'Männchen entwickeln'),
    (r'Males have', 'Männchen haben'),
    (r'Females develop', 'Weibchen entwickeln'),
    (r'Females have', 'Weibchen haben'),
    (r'bottom-dwellers', 'Bodenbewohner'),
    (r'bottom dwellers', 'Bodenbewohner'),
    (r'armored', 'gepanzert'),
    (r'schooler', 'Schwarmfisch'),
    (r'schooling', 'Schwarm'),
    (r'Peaceful', 'Friedlich'),
    (r'peaceful', 'friedlich'),
    (r'Active', 'Aktiv'),
    (r'active', 'aktiv'),
    (r'Hardy', 'Robust'),
    (r'hardy', 'robust'),
    (r'Unique', 'Einzigartig'),
    (r'unique', 'einzigartig'),
    (r'Beautiful', 'Wunderschön'),
    (r'beautiful', 'wunderschön'),
    (r'Colorful', 'Farbenfroh'),
    (r'colorful', 'farbenfroh'),
    (r'Elegant', 'Elegant'),
    (r'elegant', 'elegant'),
    (r'Stunning', 'Atemberaubend'),
    (r'stunning', 'atemberaubend'),
    (r'Distinctive', 'Markant'),
    (r'distinctive', 'markant'),
    (r'Popular', 'Beliebt'),
    (r'popular', 'beliebt'),
    (r'Adorable', 'Entzückend'),
    (r'adorable', 'entzückend'),
    (r'Attractive', 'Attraktiv'),
    (r'attractive', 'attraktiv'),
    (r'Delicate', 'Zart'),
    (r'delicate', 'zart'),
    (r'Brilliant', 'Brillant'),
    (r'brilliant', 'brillant'),
    (r'dwarf cichlid', 'Zwergbuntbarsch'),
    (r'labyrinth fish', 'Labyrinthfisch'),
    (r'with vibrant colors', 'mit lebhaften Farben'),
    (r'than females', 'als Weibchen'),
    (r'extended fins', 'verlängerte Flossen'),
    (r'displays', 'zeigt'),
    (r'breeding', 'Zucht'),
    (r'breeds', 'züchtet'),
    (r'Breeds prolifically', 'Züchtet reichlich'),
    (r'internal organs', 'innere Organe'),
    (r'transparent body', 'durchsichtiger Körper'),
    (r'completely transparent', 'vollständig durchsichtig'),
    (r'iridescent', 'schillernd'),
    (r'coloration', 'Färbung'),
    (r'variety is popular', 'Variante ist beliebt'),
    (r'intensifies', 'verstärkt sich'),
    (r'during breeding', 'während der Zucht'),
    (r'indicates health', 'zeigt Gesundheit an'),
    (r'swims at', 'schwimmt in'),
    (r'upward angle', 'aufwärtigem Winkel'),
    (r'runs along', 'verläuft entlang'),
    (r'showing', 'zeigt'),
    (r'named after', 'benannt nach'),
    (r'famous aquascaper', 'berühmten Aquascaper'),
    (r'won\'t reproduce in freshwater', 'vermehrt sich nicht in Süßwasser'),
    (r'Many patterns', 'Viele Muster'),
    (r'stays small', 'bleibt klein'),
    (r'bristles on their nose', 'Borsten auf der Nase'),
    (r'on their nose', 'auf der Nase'),
    (r'including black beard algae', 'einschließlich Bartalgen'),
    (r'confused with', 'verwechselt mit'),
    (r'Fine leopard spots', 'Feine Leopardenflecken'),
    (r'spotted', 'gefleckt'),
    (r'striped', 'gestreift'),
    (r'long barbels', 'lange Barteln'),
    (r'panda-like markings', 'pandaähnliche Markierungen'),
    (r'tolerates warmer water', 'verträgt wärmeres Wasser'),
    (r'from Lake', 'aus dem See'),
    (r'in Papua New Guinea', 'in Papua-Neuguinea'),
    (r'turquoise-blue', 'türkisblau'),
    (r'fiery red', 'feuerrot'),
    (r'flaring gills', 'aufgeblähten Kiemen'),
    (r'copper', 'kupfer'),
    (r'coppery', 'kupferfarben'),
    (r'silvery', 'silbrig'),
    (r'fin tips', 'Flossenspitzen'),
    (r'wedge marking', 'Keilmarkierung'),
    (r'heart-shaped spot', 'herzförmiger Fleck'),
    (r'glowing', 'leuchtend'),
    (r'smoky grey', 'rauchgrau'),
    (r'black markings', 'schwarze Markierungen'),
    (r'black stripe', 'schwarzer Streifen'),
    (r'red nose', 'rote Nase'),
    (r'from Madagascar', 'aus Madagaskar'),
    (r'Yellow body', 'Gelber Körper'),
    (r'West African', 'Westafrikanisch'),
    (r'bright pink belly', 'leuchtend rosa Bauch'),
    (r'dorsal fin', 'Rückenflosse'),
    
    # More common phrases
    (r'One of the most', 'Einer der'),
    (r'aquarium fish', 'Aquarienfische'),
    (r'blue and red', 'blau und rot'),
    (r'Must be kept in schools', 'Muss in Schwärmen gehalten werden'),
    (r'Must be kept', 'Muss gehalten werden'),
    (r'great for', 'toll für'),
    (r'unheated tanks', 'unbeheizte Aquarien'),
    (r'coldwater fish', 'Kaltwasserfisch'),
    (r'Tiny algae eaters', 'Winzige Algenfresser'),
    (r'Very gentle', 'Sehr sanft'),
    (r'gentle', 'sanft'),
    (r'coloring', 'Färbung'),
    (r'that are great', 'die toll sind'),
    (r'that are', 'die sind'),
    (r'with black', 'mit schwarzen'),
    (r'with red', 'mit roten'),
    (r'with blue', 'mit blauen'),
    (r'with yellow', 'mit gelben'),
    (r'with white', 'mit weißen'),
    (r'with orange', 'mit orangen'),
    (r'blue', 'blau'),
    (r'red', 'rot'),
    (r'yellow', 'gelb'),
    (r'orange', 'orange'),
    (r'green', 'grün'),
    (r'black', 'schwarz'),
    (r'white', 'weiß'),
    (r'pink', 'rosa'),
    (r'purple', 'lila'),
    (r'silver', 'silber'),
    (r'gold', 'gold'),
    (r'body', 'Körper'),
    (r'eyes', 'Augen'),
    (r'tail', 'Schwanz'),
    (r'fins', 'Flossen'),
    (r'pattern', 'Muster'),
    (r'stripe', 'Streifen'),
    (r'spot', 'Fleck'),
    (r'spots', 'Flecken'),
    
    # Even more phrases
    (r'Predatory snail', 'Räuberische Schnecke'),
    (r'that eats pest snails', 'die Schädlingsschnecken frisst'),
    (r'pest snails', 'Schädlingsschnecken'),
    (r'Not a shark but', 'Kein Hai, sondern'),
    (r'a large cyprinid', 'ein großer Karpfenfisch'),
    (r'Often bought small', 'Oft klein gekauft'),
    (r'gets massive', 'wird riesig'),
    (r'Round-bodied', 'Rundkörprig'),
    (r'molly variant', 'Molly-Variante'),
    (r'Slower swimmer', 'Langsamerer Schwimmer'),
    (r'due to', 'aufgrund'),
    (r'body shape', 'Körperform'),
    (r'Filter feeding', 'Filterfressend'),
    (r'that fans water', 'der Wasser fächert'),
    (r'for particles', 'für Partikel'),
    (r'Fascinating behavior', 'Faszinierendes Verhalten'),
    (r'fascinating', 'faszinierend'),
    (r'display to each other', 'zeigen sich gegenseitig'),
    (r'harmlessly', 'harmlos'),
    (r'larger tetra', 'größerer Salmler'),
    (r'Vibrant', 'Lebhaft'),
    (r'vibrant', 'lebhaft'),
    (r'color variety', 'Farbvariante'),
    (r'cherry shrimp', 'Kirschgarnele'),
    (r'Same easy care', 'Gleiche einfache Pflege'),
    (r'Same care', 'Gleiche Pflege'),
    (r'easy care', 'einfache Pflege'),
    (r'long fin rays', 'lange Flossenstrahlen'),
    (r'tetra with', 'Salmler mit'),
    (r'shrimp with', 'Garnele mit'),
    (r'fish with', 'Fisch mit'),
    (r'with', 'mit'),
    (r'brown', 'braun'),
    (r'larger', 'größer'),
    (r'smaller', 'kleiner'),
    (r'longer', 'länger'),
    (r'shorter', 'kürzer'),
    
    # Even more phrases
    (r'micro fish', 'Mikrofisch'),
    (r'Perfect for nano tanks', 'Perfekt für Nano-Aquarien'),
    (r'Perfect for', 'Perfekt für'),
    (r'nano tanks', 'Nano-Aquarien'),
    (r'Primarily eats wood', 'Frisst hauptsächlich Holz'),
    (r'rather than algae', 'anstatt Algen'),
    (r'Gets very large', 'Wird sehr groß'),
    (r'despite small sale size', 'trotz kleiner Verkaufsgröße'),
    (r'Not suitable for most tanks', 'Nicht für die meisten Aquarien geeignet'),
    (r'Not suitable for', 'Nicht geeignet für'),
    (r'most tanks', 'die meisten Aquarien'),
    (r'that breeds prolifically', 'der sich reichlich vermehrt'),
    (r'breeds prolifically', 'vermehrt sich reichlich'),
    (r'when breeding', 'beim Züchten'),
    (r'torpedo-shaped', 'torpedoförmig'),
    (r'needing space', 'braucht Platz'),
    (r'swimmer', 'Schwimmer'),
    (r'Sparkling scales', 'Glitzernde Schuppen'),
    (r'that shimmer', 'die schimmern'),
    (r'like diamonds', 'wie Diamanten'),
    (r'Adults are truly', 'Erwachsene sind wirklich'),
    (r'King of the aquarium', 'König des Aquariums'),
    (r'disc-shaped', 'scheibenförmig'),
    (r'requiring expert care', 'erfordert Expertenpflege'),
    (r'expert care', 'Expertenpflege'),
    (r'Tiny', 'Winzig'),
    (r'tiny', 'winzig'),
    (r'Small', 'Klein'),
    (r'small', 'klein'),
    (r'Large', 'Groß'),
    (r'large', 'groß'),
    (r'barb with', 'Barbe mit'),
    (r'barb', 'Barbe'),
    (r'pleco', 'Wels'),
    (r'cichlid', 'Buntbarsch'),
    (r'cichlids', 'Buntbarsche'),
    (r'rasbora', 'Rasbora'),
    
    # Final batch
    (r'Burrowing snail', 'Grabende Schnecke'),
    (r'that aerates substrate', 'die das Substrat belüftet'),
    (r'aerates substrate', 'belüftet Substrat'),
    (r'substrate', 'Substrat'),
    (r'Flat-bodied', 'Flachkörprig'),
    (r'Flat-coiled', 'Flach gewickelt'),
    (r'loach adapted for', 'Schmerle angepasst für'),
    (r'fast-flowing water', 'schnell fließendes Wasser'),
    (r'Needs high oxygen', 'Benötigt viel Sauerstoff'),
    (r'high oxygen', 'viel Sauerstoff'),
    (r'that breed prolifically', 'die sich reichlich vermehren'),
    (r'Good cleanup crew', 'Gutes Reinigungsteam'),
    (r'cleanup crew', 'Reinigungsteam'),
    (r'confused with', 'verwechselt mit'),
    (r'More territorial', 'Territorialer'),
    (r'less effective at', 'weniger effektiv bei'),
    (r'Pearlescent', 'Perlmuttartig'),
    (r'pearlescent', 'perlmuttartig'),
    (r'sheen', 'Glanz'),
    (r'iridescent', 'schillernd'),
    (r'danio with', 'Bärbling mit'),
    (r'danio', 'Bärbling'),
    (r'cory that swims', 'Panzerwels der schwimmt'),
    (r'cory', 'Panzerwels'),
    (r'mid-water', 'auf mittlerer Höhe'),
    (r'more than other species', 'mehr als andere Arten'),
    (r'other species', 'andere Arten'),
    (r'in groups', 'in Gruppen'),
    (r'loach', 'Schmerle'),
    (r'snail', 'Schnecke'),
    (r'snails', 'Schnecken'),
    (r'Stays reasonably small', 'Bleibt angemessen klein'),
    (r'Good alternative to', 'Gute Alternative zum'),
    (r'alternative to', 'Alternative zum'),
    (r'common pleco', 'gewöhnlichen Wels'),
]

def translate_content(content):
    """Apply all translations to content."""
    for pattern, replacement in TRANSLATIONS:
        content = re.sub(pattern, replacement, content)
    return content

def process_fish_page(fish_id):
    """Process a single fish page."""
    en_path = os.path.join(EN_FISH_DIR, fish_id, "index.html")
    de_path = os.path.join(DE_FISH_DIR, fish_id, "index.html")
    
    if not os.path.exists(en_path):
        print(f"  Skipping {fish_id} - no English page")
        return False
    
    # Read English content
    with open(en_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Translate
    content = translate_content(content)
    
    # Update canonical URL
    content = content.replace(
        f'fishfinder.guide/fish/{fish_id}/',
        f'fishfinder.guide/de/fische/{fish_id}/'
    )
    
    # Add/update hreflang tags
    if 'hreflang' not in content:
        hreflang = f'''    <link rel="alternate" hreflang="en" href="https://fishfinder.guide/fish/{fish_id}/">
    <link rel="alternate" hreflang="es" href="https://fishfinder.guide/es/peces/{fish_id}/">
    <link rel="alternate" hreflang="de" href="https://fishfinder.guide/de/fische/{fish_id}/">
'''
        content = content.replace('<link rel="canonical"', hreflang + '    <link rel="canonical"')
    else:
        # Add German hreflang if missing
        if 'hreflang="de"' not in content:
            content = content.replace(
                f'<link rel="alternate" hreflang="es" href="https://fishfinder.guide/es/peces/{fish_id}/">',
                f'''<link rel="alternate" hreflang="es" href="https://fishfinder.guide/es/peces/{fish_id}/">
    <link rel="alternate" hreflang="de" href="https://fishfinder.guide/de/fische/{fish_id}/">'''
            )
    
    # Create directory and write
    os.makedirs(os.path.dirname(de_path), exist_ok=True)
    with open(de_path, 'w', encoding='utf-8') as f:
        f.write(content)
    
    return True

def main():
    """Process all fish pages."""
    # Get list of fish from English directory
    fish_ids = [d for d in os.listdir(EN_FISH_DIR) 
                if os.path.isdir(os.path.join(EN_FISH_DIR, d))]
    
    print(f"Found {len(fish_ids)} fish to process")
    
    success = 0
    for fish_id in sorted(fish_ids):
        if process_fish_page(fish_id):
            success += 1
    
    print(f"\nDone! Created {success} German fish pages in {DE_FISH_DIR}/")

if __name__ == "__main__":
    main()
