// German fish name translations
const FISH_NAMES_DE = {
    'neon-tetra': 'Neonsalmler',
    'cardinal-tetra': 'Roter Neon',
    'betta-fish': 'Kampffisch',
    'guppy': 'Guppy',
    'platy': 'Platy',
    'molly': 'Molly',
    'balloon-molly': 'Ballon-Molly',
    'swordtail': 'Schwertträger',
    'endler-livebearer': 'Endler Guppy',
    'corydoras-catfish': 'Panzerwels',
    'bronze-cory': 'Metallpanzerwels',
    'panda-cory': 'Pandapanzerwels',
    'sterbai-cory': 'Sterbas Panzerwels',
    'pygmy-cory': 'Zwergpanzerwels',
    'angelfish': 'Skalar',
    'discus': 'Diskus',
    'german-blue-ram': 'Schmetterlingsbuntbarsch',
    'bolivian-ram': 'Bolivianischer Schmetterlingsbuntbarsch',
    'apistogramma-cacatuoides': 'Kakadu-Zwergbuntbarsch',
    'apistogramma-borellii': 'Borellis Zwergbuntbarsch',
    'convict-cichlid': 'Zebrabuntbarsch',
    'firemouth-cichlid': 'Feuermaulbuntbarsch',
    'jack-dempsey': 'Jack Dempsey',
    'oscar': 'Oscar',
    'electric-blue-acara': 'Blauer Acara',
    'yellow-lab': 'Gelber Labidochromis',
    'peacock-cichlid': 'Aulonocara',
    'zebra-danio': 'Zebrabärbling',
    'celestial-pearl-danio': 'Perlhuhnbärbling',
    'giant-danio': 'Riesenbärbling',
    'gold-ring-danio': 'Goldringbärbling',
    'harlequin-rasbora': 'Keilfleckbärbling',
    'chili-rasbora': 'Moskitobärbling',
    'emerald-eye-rasbora': 'Smaragdaugenbärbling',
    'cherry-barb': 'Kirschbarbe',
    'tiger-barb': 'Sumatrabarbe',
    'checker-barb': 'Schachbrettbarbe',
    'gold-barb': 'Goldbarbe',
    'rosy-barb': 'Prachtbarbe',
    'denison-barb': 'Denisonbarbe',
    'odessa-barb': 'Odessabarbe',
    'dwarf-gourami': 'Zwergfadenfisch',
    'honey-gourami': 'Honigfadenfisch',
    'pearl-gourami': 'Mosaikfadenfisch',
    'blue-gourami': 'Blauer Fadenfisch',
    'sparkling-gourami': 'Knurrender Zwergfadenfisch',
    'paradise-fish': 'Paradiesfisch',
    'pleco-bristlenose': 'Antennenwels',
    'common-pleco': 'Gemeiner Saugwels',
    'clown-pleco': 'Clown-Harnischwels',
    'rubber-lip-pleco': 'Gummimaul-Harnischwels',
    'royal-pleco': 'Königsharnischwels',
    'otocinclus': 'Ohrgitterharnischwels',
    'kuhli-loach': 'Dornenauge',
    'clown-loach': 'Prachtschmerle',
    'yoyo-loach': 'Yoyo-Schmerle',
    'zebra-loach': 'Zebraschmerle',
    'hillstream-loach': 'Flossensauger',
    'dojo-loach': 'Schlammpeitzger',
    'dwarf-chain-loach': 'Zwergkettenschmerle',
    'siamese-algae-eater': 'Siamesische Rüsselbarbe',
    'flying-fox': 'Siamesischer Fuchs',
    'chinese-algae-eater': 'Chinesische Saugschmerle',
    'glass-catfish': 'Glaswels',
    'pictus-catfish': 'Engelantennenwels',
    'upside-down-catfish': 'Rückenschwimmender Kongowels',
    'synodontis': 'Synodontis',
    'rummy-nose-tetra': 'Rotmaulsalmler',
    'ember-tetra': 'Funkensalmler',
    'black-skirt-tetra': 'Trauermantelsalmler',
    'serpae-tetra': 'Serpasalmler',
    'congo-tetra': 'Kongosalmler',
    'lemon-tetra': 'Zitronensalmler',
    'diamond-tetra': 'Diamantsalmler',
    'emperor-tetra': 'Kaisersalmler',
    'glowlight-tetra': 'Glühlichtsalmler',
    'flame-tetra': 'Flammensalmler',
    'bleeding-heart-tetra': 'Blutherzsalmler',
    'black-phantom-tetra': 'Schwarzer Phantomsalmler',
    'buenos-aires-tetra': 'Buenos-Aires-Salmler',
    'rainbow-shark': 'Regenbogenhai',
    'red-tail-shark': 'Rotflossen-Fransenlipper',
    'boesemani-rainbow': 'Boesemans Regenbogenfisch',
    'turquoise-rainbow': 'Türkis-Regenbogenfisch',
    'celebes-rainbow': 'Celebes Sonnenstrahlfisch',
    'forktail-rainbow': 'Gabelschwanz-Regenbogenfisch',
    'gertrudae-rainbow': 'Gertrudae Regenbogenfisch',
    'threadfin-rainbow': 'Fadenflosser',
    'cherry-shrimp': 'Rote Zwerggarnele',
    'amano-shrimp': 'Amanogarnele',
    'ghost-shrimp': 'Glas-/Geistergarnele',
    'crystal-red-shrimp': 'Crystal Red Garnele',
    'blue-velvet-shrimp': 'Blue Velvet Garnele',
    'bamboo-shrimp': 'Bambusgarnele',
    'vampire-shrimp': 'Vampirgarnele',
    'nerite-snail': 'Geweihschnecke',
    'mystery-snail': 'Apfelschnecke',
    'assassin-snail': 'Raubschnecke',
    'ramshorn-snail': 'Posthornschnecke',
    'malaysian-trumpet-snail': 'Turmdeckelschnecke',
    'rabbit-snail': 'Kaninchenschnecke',
    'clown-killifish': 'Clown-Killifisch',
    'golden-wonder-killifish': 'Goldener Wunderkärpfling',
    'blue-notho': 'Rachows Prachtgrundkärpfling',
    'african-butterfly-fish': 'Afrikanischer Schmetterlingsfisch',
    'hatchetfish': 'Beilbauchfisch',
    'bala-shark': 'Haibarbe',
    'red-eye-tetra': 'Rotaugen-Moenkhausia',
    'silver-dollar': 'Silberdollar',
    'white-cloud': 'Kardinalfisch'
};

function getFishNameDE(fishId, fallback) {
    return FISH_NAMES_DE[fishId] || fallback;
}
