// French fish name translations
const FISH_NAMES_FR = {
    'neon-tetra': 'Néon bleu',
    'betta-fish': 'Combattant',
    'guppy': 'Guppy',
    'corydoras-catfish': 'Corydoras',
    'angelfish': 'Scalaire',
    'platy': 'Platy',
    'molly': 'Molly',
    'cherry-barb': 'Barbus cerise',
    'zebra-danio': 'Danio zébré',
    'dwarf-gourami': 'Gourami nain',
    'pleco-bristlenose': 'Ancistrus',
    'cardinal-tetra': 'Cardinalis',
    'harlequin-rasbora': 'Rasbora arlequin',
    'german-blue-ram': 'Ramirezi',
    'kuhli-loach': 'Loche kuhli',
    'black-skirt-tetra': 'Veuve noire',
    'rummy-nose-tetra': 'Nez rouge',
    'emperor-tetra': 'Tétra empereur',
    'congo-tetra': 'Tétra du Congo',
    'serpae-tetra': 'Tétra serpae',
    'glowlight-tetra': 'Tétra lumineux',
    'diamond-tetra': 'Tétra diamant',
    'flame-tetra': 'Tétra flamme',
    'black-phantom-tetra': 'Tétra fantôme noir',
    'lemon-tetra': 'Tétra citron',
    'bleeding-heart-tetra': 'Tétra cœur saignant',
    'buenos-aires-tetra': 'Tétra de Buenos Aires',
    'silvertip-tetra': 'Tétra à pointes blanches',
    'red-eye-tetra': 'Tétra aux yeux rouges',
    'x-ray-tetra': 'Tétra rayon X',
    'penguin-tetra': 'Tétra pingouin',
    'swordtail': 'Xipho',
    'endler-livebearer': 'Guppy d’Endler',
    'sailfin-molly': 'Molly voile',
    'balloon-molly': 'Molly ballon',
    'otocinclus': 'Otocinclus',
    'pictus-catfish': 'Pimelodus pictus',
    'glass-catfish': 'Silure de verre',
    'upside-down-catfish': 'Poisson-chat nageur inversé',
    'panda-cory': 'Corydoras panda',
    'bronze-cory': 'Corydoras bronze',
    'peppered-cory': 'Corydoras poivré',
    'sterbai-cory': 'Corydoras de Sterba',
    'pygmy-cory': 'Corydoras pygmée',
    'julii-cory': 'Corydoras julii',
    'discus': 'Discus',
    'apistogramma-cacatuoides': 'Apistogramma cacatoès',
    'apistogramma-borellii': 'Apistogramma de Borelli',
    'kribensis': 'Kribensis',
    'oscar': 'Oscar',
    'convict-cichlid': 'Cichlidé zébré',
    'jack-dempsey': 'Jack Dempsey',
    'electric-blue-acara': 'Acara bleu électrique',
    'firemouth-cichlid': 'Cichlidé bouche de feu',
    'severum': 'Severum',
    'yellow-lab': 'Labido jaune',
    'peacock-cichlid': 'Cichlidé paon',
    'jewel-cichlid': 'Cichlidé joyau',
    'tiger-barb': 'Barbus de Sumatra',
    'rosy-barb': 'Barbus rosé',
    'gold-barb': 'Barbus doré',
    'denison-barb': 'Barbus de Denison',
    'odessa-barb': 'Barbus d’Odessa',
    'checker-barb': 'Barbus damier',
    'chili-rasbora': 'Rasbora chili',
    'celestial-pearl-danio': 'Danio céleste',
    'emerald-eye-rasbora': 'Rasbora aux yeux émeraude',
    'scissortail-rasbora': 'Rasbora queue de ciseaux',
    'lambchop-rasbora': 'Rasbora espei',
    'phoenix-rasbora': 'Rasbora phénix',
    'clown-loach': 'Loche clown',
    'yoyo-loach': 'Loche yoyo',
    'hillstream-loach': 'Loche de torrent',
    'dojo-loach': 'Loche dojo',
    'zebra-loach': 'Loche zébrée',
    'dwarf-chain-loach': 'Loche naine',
    'pearl-gourami': 'Gourami perlé',
    'honey-gourami': 'Gourami miel',
    'moonlight-gourami': 'Gourami clair de lune',
    'blue-gourami': 'Gourami bleu',
    'kissing-gourami': 'Gourami embrasseur',
    'sparkling-gourami': 'Gourami grogneur',
    'paradise-fish': 'Poisson paradis',
    'cherry-shrimp': 'Crevette cerise',
    'amano-shrimp': 'Crevette Amano',
    'ghost-shrimp': 'Crevette fantôme',
    'crystal-red-shrimp': 'Crevette Crystal Red',
    'blue-velvet-shrimp': 'Crevette Blue Velvet',
    'bamboo-shrimp': 'Crevette bambou',
    'nerite-snail': 'Escargot nérite',
    'mystery-snail': 'Escargot pomme',
    'ramshorn-snail': 'Planorbe',
    'assassin-snail': 'Escargot assassin',
    'malaysian-trumpet-snail': 'Mélanoïde',
    'rabbit-snail': 'Escargot lapin',
    'clown-killifish': 'Killi clown',
    'golden-wonder-killifish': 'Panchax doré',
    'blue-notho': 'Notho bleu',
    'least-killifish': 'Heterandria formosa',
    'boesemani-rainbow': 'Poisson arc-en-ciel de Boeseman',
    'neon-dwarf-rainbow': 'Arc-en-ciel néon nain',
    'turquoise-rainbow': 'Arc-en-ciel turquoise',
    'madagascar-rainbow': 'Arc-en-ciel de Madagascar',
    'red-irian-rainbow': 'Arc-en-ciel rouge d’Irian',
    'celebes-rainbow': 'Arc-en-ciel des Célèbes',
    'forktail-rainbow': 'Arc-en-ciel à queue fourchue',
    'gertrudae-rainbow': 'Arc-en-ciel de Gertrude',
    'white-cloud-mountain-minnow': 'Néon du pauvre',
    'leopard-danio': 'Danio léopard',
    'pearl-danio': 'Danio perlé',
    'giant-danio': 'Danio géant',
    'longfin-zebra-danio': 'Danio zébré voile',
    'gold-ring-danio': 'Danio tinwini',
    'siamese-algae-eater': 'Mangeur d’algues siamois',
    'flying-fox': 'Renard volant',
    'red-tailed-shark': 'Requin à queue rouge',
    'rainbow-shark': 'Requin arc-en-ciel',
    'common-pleco': 'Pléco commun',
    'rubber-lip-pleco': 'Pléco à lèvres caoutchouc',
    'clown-pleco': 'Pléco clown',
    'royal-pleco': 'Pléco royal',
    'bala-shark': 'Requin bala',
    'tinfoil-barb': 'Barbus de Schwanenfeld'
};

function getFishNameFR(fishId, fallback) {
    return FISH_NAMES_FR[fishId] || fallback;
}
